#!/bin/bash

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew bundle
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# iterm
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/Dropbox/Apps/iTerm2"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# install Prezto
zsh
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" --depth=1
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
chsh -s /bin/zsh
ln -s ~/.dotfiles/prezto/prompt_digeni_setup ~/.zprezto/modules/prompt/functions/prompt_digeni_setup
# install zsh-autosuggestions
git clone git://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# set vscode
cd "~/Library/Application Support/Code/User/"
rm -rf settings.json
ln -s ~/.dotfiles/vscode/settings.json "~/Library/Application Support/Code/User/settings.json"
ln -s ~/.dotfiles/vscode/keybindings.json "~/Library/Application Support/Code/User/keybindings.json"
ln -s ~/.dotfiles/vscode/snippets/html.erb.json "~/Library/Application Support/Code/User/snippets/html.erb.json"
cd ~

# install iptable rules from https://github.com/ranmocy/chnroutes
#mkdir -p ~/scripts
#git clone git@github.com:ranmocy/chnroutes.git
#cd chnroutes && python chnroutes.py -p mac -t ipsec && cd ..
#touch vpnreset && chmod +x vpnreset
#cat >> vpnreset<<EOF
##!/bin/sh
#sudo sh ~/scripts/phase1-down.sh
#sudo sh ~/scripts/phase1-up.sh
#exit
#EOF

# install rbenv
#git clone https://github.com/rbenv/rbenv.git ~/.rbenv --depth=1
#git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build --depth=1

# link dotfiles
vim +PlugInstall +qall
ln -s ~/.dotfiles/.ctags ~/.ctags
ln -s ~/.dotfiles/.gemrc ~/.gemrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc

# aria2
#mkdir -p ~/.aria2
#ln -s ~/.dotfiles/.aria2/aria2.conf ~/.aria2/aria2.conf
