#!/bin/bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install wget
brew install curl
# brew install git

# install vim
brew install python3
brew install ctags
brew install the_silver_searcher
brew install vim --with-lua
brew install macvim --with-lua
brew linkapps macvim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# install emacs
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-spacemacs-icon
git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d --depth=1

brew install z

# install aria2
brew install aria2
mkdir -p ~/.aria2
ln -s ~/.dotfiles/.aria2/aria2.conf ~/.aria2/aria2.conf

# install dnsmasq
brew instal dnsmasq
ln -s ~/.dotfiles/dnsmasq/dnsmasq.conf /usr/local/etc/dnsmasq.conf
sudo brew services start dnsmasq

# install apps
brew cask install google-chrome
brew cask install iterm2
brew cask install the-unarchiver
brew cask install sublime-text
# brew cask install dropbox
# brew cask install karabiner
# brew cask install sequel-pro
brew cask install appcleaner
# brew cask install coteditor
brew cask install datagrip
brew cask install firefox
# brew cask install lantern
# brew cask install vlc
brew cask install youdao
brew cask install macdown
brew cask install wwdc

# install Prezto
zsh
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" --depth=1
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
chsh -s /bin/zsh
ln -s ~/.dotfiles/prezto/prompt_digeni_setup ~/.zprezto/modules/prompt/functions/prompt_digeni_setup
# install zsh-autosuggestions
git clone git://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# set sublime text
open "/Applications/Sublime Text.app"
cd ~/Library/"Application Support"/"Sublime Text 3"/Packages
rm -rf User
ln -s ~/.dotfiles/sublime_text ~/Library/"Application Support"/"Sublime Text 3"/Packages/User
cd ~
# go https://packagecontrol.io/installation and Ctrl + ` to paste then install

# set karabiner
#rm -f ~/Library/Application Support/Karabiner/private.xml
#ln -s ~/.dotfiles/karabiner/private.xml ~/Library/"Application Support"/Karabiner/private.xml
#cd ~

# install iptable rules from https://github.com/ranmocy/chnroutes
#mkdir -p ~/scripts
#git clone git@github.com:ranmocy/chnroutes.git
#cd chnroutes && python chnroutes.py -p mac -t ipsec && cd ..
#touch vpnreset && chmod +x vpnreset
#cat >> vpnreset<<EOF
##!/bin/sh
#sudo sh ~/scripts/phase1-down.sh
#sudo sh ~/scripts/phase1-up.sh
#exit
#EOF

# install rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv --depth=1
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build --depth=1

# link dotfiles
ln -s ~/.dotfiles/.spacemacs ~/.spacemacs
ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
vim +PlugInstall +qall
ln -s ~/.dotfiles/.ctags ~/.ctags
ln -s ~/.dotfiles/.gemrc ~/.gemrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc
